version: '3'
services:
    backend:
        build:
            context: ./services/backend
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: skripsi-backend
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-5000}:5000'
        environment:
            WWWUSER: '${WWWUSER}'
            FLASK_ENV: development
            FLASK_APP: app.py
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: '${DB_DATABASE}'
            DB_USER: '${DB_USERNAME}'
            DB_PASS: '${DB_PASSWORD}'
        volumes:
            - './services/backend:/var/www/html'
        networks:
            - skripsi
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'skripsi-mysql:/var/lib/mysql'
        networks:
            - skripsi
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    skripsi:
        driver: bridge
volumes:
    skripsi-mysql:
        driver: local
